### ISSUE TITLE
this.getColumnType is not a function

### ISSUE THREAD

**Issue by LKTSNR** [whawker/TweetDeck-Chrome-Trends#4]
![captura](https://user-images.githubusercontent.com/38336487/38710922-085ebcfc-3e99-11e8-87b8-e5e49901a1fe.JPG)
This error appears when trying to enter tweetdeck. After clicking on "Log in", you can enter, but the "Trends" column never loads.

**Comment by cinemadraft** [comment]
Same here

**Comment by netocavalcanti** [comment]
Same here

**Comment by rpodric** [comment]
Thought it might be just me. I've disabled it for now.

I wonder, could this script be gifted to Tweeten to incorporate there?  That's an extension that's essentially a glorified userscript for Tweetdeck--but it notably doesn't have this feature!

**Comment by EvanWinstanley** [comment]
I was able to resolve by editing the script directly and removing lines 15 - 19
https://github.com/whawker/TweetDeck-Chrome-Trends/blob/master/tampermonkey.user.js#L15-L19

It seems a recent Tweetdeck update has removed the `getColumnType` function from the column object prototype, with no obvious replacement. There is a field on the column object called `model.type` but this didn't seem relevant in my (very limited) testing. So I just removed the override of `isFilterable` function completely and it seems to work fine.

**Comment by whawker** [comment]
Sorry all, I'm on holiday at the moment without a laptop, so I can't make the changes.

If someone could open a PR, I'd be happy to merge!

**Comment by netocavalcanti** [comment]
Removing the lines 15 to 19 don't fix the problem to me. The trends are back but every column just keeps loading including the trend without the option to choose location.

@whawker Take your time and enjoy your holiday. We can wait.

**Comment by EvanWinstanley** [comment]
@whawker PR created https://github.com/whawker/TweetDeck-Chrome-Trends/pull/5

Just double check what I'm doing is right, it's not totally clear to me what that method was doing 😰

**Comment by Zhangsun321** [comment]
When you do get around to fixing it, thanks A LOT..

**Comment by whawker** [comment]
Hi all, this should be fixed now. If you open the Tampermonkey dashboard then trigger an update, the new version is 4.4.0

**Comment by netocavalcanti** [comment]
@whawker Working perfectly again. Thank you!
Have a great week.

**Comment by LKTSNR** [comment]
Thanks a lot @whawker!!
