### ISSUE TITLE
Trends not loading

### ISSUE THREAD

**Issue by LKTSNR** [whawker/TweetDeck-Chrome-Trends#7]
![consola](https://user-images.githubusercontent.com/38336487/42189503-df6a41b0-7e2e-11e8-9de7-e924c6fdf8a2.PNG)

'wrap' error

**Comment by whawker** [comment]
Hi, this is already fixed in [v4.5](https://github.com/whawker/TweetDeck-Chrome-Trends/commit/c6fa8c96561a17c0e401a9654b36539a4f196e7f). Try triggering an update from your Tampermonkey dashboard

**Comment by LKTSNR** [comment]
Oh, thanks a lot @whawker, updating right now!
;)
